# this package
from ._definitions import CSS3 as CSS3  # noqa: F401
from ._normalization import normalize_hex as normalize_hex  # noqa: F401
from ._normalization import normalize_integer_triplet as normalize_integer_triplet  # noqa: F401
from ._normalization import normalize_percent_triplet as normalize_percent_triplet  # noqa: F401
from ._types import IntegerRGB as IntegerRGB
from ._types import IntTuple as IntTuple
from ._types import PercentRGB as PercentRGB
from ._types import PercentTuple as PercentTuple

def name_to_hex(name: str, spec: str = ...) -> str: ...
def name_to_rgb(name: str, spec: str = ...) -> IntegerRGB: ...
def name_to_rgb_percent(name: str, spec: str = ...) -> PercentRGB: ...
def hex_to_name(hex_value: str, spec: str = ...) -> str: ...
def hex_to_rgb(hex_value: str) -> IntegerRGB: ...
def hex_to_rgb_percent(hex_value: str) -> PercentRGB: ...
def rgb_to_name(rgb_triplet: IntTuple, spec: str = ...) -> str: ...
def rgb_to_hex(rgb_triplet: IntTuple) -> str: ...
def rgb_to_rgb_percent(rgb_triplet: IntTuple) -> PercentRGB: ...
def rgb_percent_to_name(rgb_percent_triplet: PercentTuple, spec: str = ...) -> str: ...
def rgb_percent_to_hex(rgb_percent_triplet: PercentTuple) -> str: ...
def rgb_percent_to_rgb(rgb_percent_triplet: PercentTuple) -> IntegerRGB: ...
