# this package
from ._types import HTML5SimpleColor as HTML5SimpleColor
from ._types import IntTuple as IntTuple

def html5_parse_simple_color(value: str) -> HTML5SimpleColor: ...
def html5_serialize_simple_color(simple_color: IntTuple) -> str: ...
def html5_parse_legacy_color(value: str) -> HTML5SimpleColor: ...
